export { default as Home } from "./Home";
export { default as Playlist } from "./Playlist";
export { default as History } from "./History";
export { default as Trending } from "./Trending";
export { default as WatchLater } from "./WatchLater";
export { default as WatchVideo } from "./WatchVideo";
export { default as YourVideos } from "./YourVideos";
export { default as LikedVideos } from "./LikedVideos";
export { default as Videos } from "./Videos";
